- hosts: vagrant
  sudo: yes
  gather_facts: no # サーバ情報収集をスキップ
  tasks:
    
    - name: 疎通確認
      ping:
      tags: ping
    
    - name: update server
      apt: update_cache=yes
      apt: upgrade=dist
      tags: update
      
    - name: パッケージのインストール
      apt: pkg={{ item }} state=latest
      with_items:
          - git
          - vim
          - tree
          - wget
          - apache2
          - mysql-server
          - php5
          - php5-mcrypt
          - python-mysqldb # for mysql-module
      tags: common-packages
      
    - name: phpinfoを置く
      shell: rm /var/www/html/_index.html
      shell: echo '<?php phpinfo();' > /var/www/html/index.php
      
    # 各値は変数にする
    - name: データベース作成 'ansible'
      mysql_db: name=ansible state=present encoding=utf8
      tags: mysql
      
    - name: MySQLユーザ作成
      mysql_user: >
        name=hoge
        password=fuga
        priv=ansible.*:ALL
        state=present
      tags: mysql
      
    - name: サービスの(再)起動
      service: name={{ item }} state=reloaded enabled=yes
      with_items:
          - apache2
          - mysql
      tags: reload